### ISSUE TITLE
Investigate hachiko timeout test failures...

### ISSUE THREAD

**Issue by Connoropolous** [h-be/acorn-hc#61]
Tests on master have now failed, though I was under the impression that on the branch before merge they were passing. A quick scan shows Hachiko timeout related issues, which suggests a consistency model issue

@thedavidmeister would be able to take a look? 

as an FYI to @thedavidmeister we're running tests with sim2h networking type, and pointing it to `wss://sim2h.harris-braun.org:9000` which is running 0.0.40-alpha1 just like our Conductor and HDK versions

We might want to update nix to 0.0.52 holonix though...

**Comment by thedavidmeister** [comment]
@Connoropolous i think wait til the `0.0.41-alpha1` before getting deep on this because i know there have been some hachiko improvements lately

**Comment by Connoropolous** [comment]
Speaking of how are app devs supposed to know which version of tryorama they should be on, to match the version of Holochain?

**Comment by thedavidmeister** [comment]
@Connoropolous hmm, yeah i'm not sure because there seem to be new versions of tryorama coming out regularly atm :/ i got tripped up by this a few times also

**Comment by Connoropolous** [comment]
App dev is really a three way (at least) triangle of dependencies, with 

conductor/hc <> hdk <> tryorama
version matching between hdk and and conductor/hc can be lined up easily because of the release process, but tryorama is decoupled

**Comment by Connoropolous** [comment]
maybe you can raise the issue sometime internally?

**Comment by thedavidmeister** [comment]
@Connoropolous yes i agree totally, although i don't have any clear solution off the top of my head

also in the future it is likely that hdk would be separated from the conductor because there is no real reason they need to be locked into the same release cycle, e.g. we have the problem that people churn hdk versions because "it seems like they should" when literally nothing has changed in the underlying code

the problem harder with tryorama because hdk/hc are in rust while tryorama is in node, so there's no way to have `Cargo.toml` and `package.json` "talk to each other" via the compiler

i'll raise some visibility on MM and see what people think...

**Comment by maackle** [comment]
@Connoropolous as far as I know, there have been no changes to tryorama that would make it work for some conductor/hdk version and not others. Backward compatibility is always kept in mind. So, it's intended that any version of tryorama should work with any conductor version right now. Have you found that not to be the case?

Tryorama's main coupling to the conductor is through the config files it generates, and the format of the config files hasn't changed appreciably in a long time, at least not for the essentials like instance configuration. The HDK also hasn't changed in a long time, and the only thing tryorama is doing is making zome calls, anyway.
