### ISSUE TITLE
Profiles hash mismatch

### ISSUE THREAD

**Issue by adappt-io** [h-be/acorn-hc#91]
Version 0.3.2
Followed build instructions, straightforward.  When running `nix-shell --run acorn-hc`  ended with

> Error while trying to boot from config: ErrorGeneric("Error while trying to create instance \"profiles-instance\": Provided DNA hash does not match actual DNA hash! QmdGgs8UFtqyV9ed7offX4znEEdZJ3QXEfUjCjBQ44Dbyv != QmRU1hYj5b1BBLcyb46qH29n5NjMJWbH5fWZrSMe3jA3ZB")

Changing the hash listed in conductor-config.toml manually to the second hash allowed me to continue.  Not sure of the implications except I suppose in a multiuser system.

**Comment by Connoropolous** [comment]
Hi @adappt-io thanks for logging an issue.

We are aware of this general problem of getting that "error message", since when the code is compiled it differs in its hash, depending on the platform. This means that the hash is almost always wrong for somebody, forcing them to manually update it like you had to.

I had previously talked one other person through it, in the Acorn chat channel on mattermost, but I will update my response from there to here, so that we can track this issue better, and work towards the solution. 

What I had posted:

There is some code in acorn-release that could help if it were ported over...
`hc hash --path dist/acorn.dna.json | awk '/DNA Hash: /{print $NF}' | tr -d '\n' > dna_address`
that will write the DNA hash/address into the file `dna_address`
Then one more step would be to auto-update the DNA line in the `conductor-config.toml`. 
P.s. I am making these notes for myself as much as for you, just thinking this would be an improvement
So there's this code for updating the conductor-config
https://github.com/h-be/acorn-release/blob/master/main.js#L65-L94

**Comment by Connoropolous** [comment]
We have this public chat channel, p.s. https://chat.holochain.org/appsup/channels/acornstateofaffairs

**Comment by adappt-io** [comment]
Thanks Connor, it's on your radar so not sure your rules but feel free to close this issue.

**Comment by Connoropolous** [comment]
I'm leaving it open cause I'm going to work on it. Right now, in fact
